### ISSUE TITLE
Can't pipe into handpipe

### ISSUE THREAD

**Issue by ollien** [handpipe/handpipe.js#3]
Hey there,

I hated that handlebars didn't support streams, so I gave your repo a shot. However, upon running the below code, I get a syntax error from within your source. Is there a fix? My node version is v0.12.4

``` javascript
var fs = require("fs")
//...
var data = {posts: posts,postCount: length}
res.writeHead({"Content-Type": "text/html"})
fs.createReadStream("./html_templates/index.html").pipe(handpipe(data)).pipe(res)
```

```
evalmachine.<anonymous>:1
(function* (ts) {var f=/&/g,c=/</g,e=/>/g,b=/\'/g,a=/\"/g,d=/[&<>\"\']/;functi
         ^
SyntaxError: Unexpected token *
    at Object.exports.runInNewContext (vm.js:68:16)
    at DestroyableTransform._flush (/Volumes/BackRoom/Dropbox/Timpani/node_modules/handpipe/apply.js:14:16)
    at DestroyableTransform.<anonymous> (/Volumes/BackRoom/Dropbox/Timpani/node_modules/handpipe/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at finishMaybe (/Volumes/BackRoom/Dropbox/Timpani/node_modules/handpipe/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (/Volumes/BackRoom/Dropbox/Timpani/node_modules/handpipe/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (/Volumes/BackRoom/Dropbox/Timpani/node_modules/handpipe/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
    at DuplexWrapper.onend (/Volumes/BackRoom/Dropbox/Timpani/node_modules/handpipe/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:199:16)
```

**Comment by ollien** [comment]
Fixed it, made an error when running handlepipe. I was running node server.js --harmony, rather than node --harmony server.js
